### ISSUE TITLE
"Zero MiniAVC" versions in CKAN sort out-of-order WRT KSP version

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#6719]
CKAN version 1.25.3
KSP version 1.4.5
Operating System: Windows 10 1803

Mod: ZeroMiniAVC, part of Malah's Quick Mods
Current Mod Maintainer: @linuxgurugamer 

CKAN metadata:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/ZeroMiniAVC/ZeroMiniAVC-v1.03.ckan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/ZeroMiniAVC/ZeroMiniAVC-v1.04.ckan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/ZeroMiniAVC/ZeroMiniAVC-v1.05.ckan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/ZeroMiniAVC/ZeroMiniAVC-1.0.5.1.ckan

Issue:  "Zero MiniAVC" versions in CKAN sort out-of-order with respect to KSP version

CKAN mod version table in order:

v1.0.5       KSP 1.3.0 - 1.3.99
v1.0.4       KSP 1.2.0 - 1.2.99
v1.0.3       KSP 1.2.0 - 1.2.99
1.0.5.1      KSP 1.4.0 - 1.4.99 

Description:

To access mods available only in KSP 1.3.x versions I explicitly knew would work in KSP 1.4.5, I enabled KSP 1.3 compatibility in the CKAN client.

I then saw the most recent version of ZeroMiniAVC offered for installation was 1.0.5, not the latest 1.0.5.1.

After discussion with the mod maintainer and further investigation, I discovered that due to naming of the mod versions in the .ckan files, they were sorting out of order with respect to the KSP version.

v1.0.5       KSP 1.3.0 - 1.3.99
v1.0.4       KSP 1.2.0 - 1.2.99
v1.0.3       KSP 1.2.0 - 1.2.99
1.0.5.1      KSP 1.4.0 - 1.4.99 

As long as KSP 1.4 was the only version set as compatible in the CKAN client, the most recent version of ZeroMiniAVC, 1.0.5.1, was offered as default.

If as well as KSP 1.4, any KPS version matching any of the other 3 .ckan's were marked as compatible, an earlier version of ZeroMiniAVC would be offered.

Workaround when KSP 1.4 and earlier KSP versions are marked as compatible: 
Explicitly install mod version 1.0.5.1 by double-clicking on it in the client.
And not selecting the offered mistaken update afterwards.

**Comment by HebaruSan** [comment]
Looks like the problem is in the version numbers on SpaceDock:

![image](https://user-images.githubusercontent.com/1559108/45972375-14ce6f00-c02b-11e8-9f5f-cbbbe02ac50d.png)

One of them starts with a "v", and the next one doesn't. Assigned @linuxgurugamer for the fix.

**Comment by Olympic1** [comment]
We could use `"x_netkan_force_v": true` to place a `v`in front of the version.

**Comment by Jacke4913** [comment]
I think such an automatic version converter would have issues.  For example, it wouldn't fix a case when more than a single 'v' is stuck onto some of the version numbers for some extra characters, like this:

v_1.2.1
1.2.2

It's also an automatic transformation in a vital feature that should be correct from upstream or appropriately adjusted with epoch numbers in the first place.  Better vigilance and correction here.

It's been a long time since I read it, but Debian Policy Manual handles this by rigorous format for version numbers, including how to incorporate upstream version numbers.  And of course it still has mistakes (in unstable etc.) and irregular changes in upstream versions and still needs epoch numbers.

**Comment by linuxgurugamer** [comment]
This was fixed with the addition of an epoch, I had apparently made a mistake when posting to Spacedock in a previous version

**Comment by HebaruSan** [comment]
It's not fixed, though, and this mod has no epoch.
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ZeroMiniAVC.netkan

**Comment by linuxgurugamer** [comment]
The problem was actually in the previous version I had released a version which was incorrect (3rd octet was something like 49).  I added the octet and deleted the bad version

**Comment by HebaruSan** [comment]
Problem still exists as originally described. Re-opening.

![image](https://user-images.githubusercontent.com/1559108/46049622-eaf67480-c11e-11e8-94b8-4471d4fb0dd8.png)

**Comment by linuxgurugamer** [comment]
Oh, I think I got this confused with another update I did.  I'll add an epoch to this, since the mod is correct

**Comment by linuxgurugamer** [comment]
Fixed with: #6723
