### ISSUE TITLE
[CustomBarnKit] CustomBarnKit-RO-1.1.20.0.ckan Meta Error?

### ISSUE THREAD

**Issue by DRVeyl** [KSP-CKAN/NetKAN#7859]
I believe CustomBarnKit-RO should be for KSP 1.7.3, and not KSP 1.8.
CustomBarnKit-RO.netkan refers to Sarbiarn's jenkins: 
`"$kref": "#/ckan/jenkins/https://ksp.sarbian.com/jenkins/job/CustomBarnKit-RO/",`

The .version file there, and contained in the zipfile, specify KSP 1.7.3:
```
    "KSP_VERSION": {
        "MAJOR": 1,
        "MINOR": 7,
        "PATCH": 3
    },
    "KSP_VERSION_MIN": {
        "MAJOR": 1,
        "MINOR": 7,
        "PATCH": 3
    },
    "KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": 7,
        "PATCH": 3
    }
```

CKAN shows CustomBarnKit 1.1.20 as valid for 1.8, which is correct.
However, it shows CustomBarnKit-RO 1.1.20 as valid for 1.8, which I believe is not.

**Comment by DasSkelett** [comment]
The remote version file referenced in the included version file states 1.8 compatibility: https://ksp.sarbian.com/jenkins/job/CustomBarnKit/lastSuccessfulBuild/artifact/CustomBarnKit/CustomBarnKit.version

But I think this reference is wrong, I guess it should be
https://ksp.sarbian.com/jenkins/job/CustomBarnKit-RO/lastSuccessfulBuild/artifact/CustomBarnKit/CustomBarnKit-RO.version (from the Jenkins project you linked).

@sarbian has to fix the reference in the included version file, then CKAN can pick up the right one.

**Comment by HebaruSan** [comment]
Looks like he generates that file with some sort of string substitution script:

- https://github.com/sarbian/CustomBarnKit/blob/master/CustomBarnKit/CustomBarnKit.version.in

... but I don't see anyplace where the source data is defined. Possibly handled by Jenkins?

**Comment by HebaruSan** [comment]
Re-reported in sarbian/CustomBarnKit#9. Hopefully that'll get the ball rolling in the right direction.

**Comment by DRVeyl** [comment]
Would a new release change the .ckan metadata for the existing release, though?  I think Sarbian would need to edit the existing release and then cause the bot to re-index it.  Possibly by PR'ing a [nop] change to the .netkan?

**Comment by HebaruSan** [comment]
> ~Would a new release change the .ckan metadata for the existing release, though? I think Sarbian would need to edit the existing release and then cause the bot to re-index it. Possibly by PR'ing a [nop] change to the .netkan?~ HebaruSan's first line in the CBK report says otherwise!

If a new release is made, we could freely edit the old release's metadata without having it overwritten by the NetKAN bot. Right now if we changed `CustomBarnKit-RO-1.1.20.ckan` to only be compatible with KSP 1.7, that change would be rolled back the next time that the bot checked it (within 2-6 hours).

**Comment by sarbian** [comment]
I fixed the build script and ran it. The version file URL is now the RO one.

Strange that no one noticed before...

**Comment by DRVeyl** [comment]
A bit strange.  RP-1 only recently got its 1.8 release published.  The install guides still have some manual steps that maybe don't need to be there, including enabling 1.7 mods as compatible.. I suspect we figured the backport release was getting picked up from that, and didn't look more carefully until yesterday. Thanks for fixing!

**Comment by HebaruSan** [comment]
Confirmed updated. Thanks for the report.

https://github.com/KSP-CKAN/CKAN-meta/commit/88a0a0adfbc2416218024ca5381090a190a93bda
